### ISSUE TITLE
Auction duration is hardcoded.

### ISSUE THREAD

**Issue by yuriy77k** [jointerinc/jointer-token#1]
@mak2296 [MIN_AUCTION_END_TIME](https://github.com/jointerinc/jointer-token/blob/592044a7e83578e14d9aff25a33d788413866009/contracts/auctionContracts/Auction.sol#L394) is constant and set to 800 seconds. But auction duration is much longer. 
I think the duration of the auction should be set in the constructor or has a setter function.

**Comment by mak2296** [comment]
Right now for testing purpose we set 800 but we can move it constructor but once it set it cant be moved

**Comment by mak2296** [comment]
This is moved constructor
