### ISSUE TITLE
Gas wasting

### ISSUE THREAD

**Issue by yuriy77k** [jointerinc/jointer-token#12]
There is a big problem with Gas wasting in all contracts.

The biggest waste of gas is due to calling functions from another contract (cross-contract calling). Each cross-contract calls use more 2000 Gas in compere with the same function in the local contract.

## 1.  The function `getAddressOf` which call `contractsRegistry.getAddressOf()`. 

This function uses very often (even several times in one function) and it makes transaction cast very high.

For example the function [checkBeforeTransfer](https://github.com/jointerinc/jointer-token/blob/58f0fc84ca25ebe66dccc59a6443494cd8adbfb1/contracts/Tokens/MainToken.sol#L63-L76):

``` solidity
    function checkBeforeTransfer(address _from, address _to)
        internal
        view
        returns (bool)
    {
        address whiteListAddress = getAddressOf(WHITE_LIST);


        if (_to != getAddressOf(SMART_SWAP)) {
            require(
                IWhiteList(whiteListAddress).main_isTransferAllowed(_from, _to),
                "ERR_NOT_HAVE_PERMISSION_TO_TRANSFER"
            );
        }
        return true;
    }
```

Here used `getAddressOf` twice. It's mean that each token transfer transaction will use 4000 more gas.  But the situation becomes worse in the Auction contract where token transfer uses many times. So it increases Gas usage in N * 4000 (where N is the number of calls token transfer function).

### Recommendation
Use global variables in each contract to hold addresses of contracts which used in it. Create function `updateAddresses()` that will update all this addresses from the `contractsRegistry`. Call `updateAddresses()` each time when change some contract address in the `contractsRegistry` (it will be very seldom).
For example:
``` solidity
    address white_list;
    address smart_swap;

    function updateAdresses() external {
        white_list = getAddressOf(WHITE_LIST);
        smart_swap = getAddressOf(SMART_SWAP);
    }
```

## 2. Cross-contract calling between Auction<>Liquidity.

In many places the Auction contract calls Liquidity and vice versa, In most cases, the functions may be located in the same contract and avoid cross-contract calling.

### Recommendation
Use separate contract only for holding tokens/fund and call their functions only for transferring tokens/funds. I.e. we need:  We should not call another contract just for calculation or getting some variable, or do it very seldom.

## 3. Using `AuctionFormula` contract for calculation.

In the last audit report was recommended to use separate contract for formulas to be able to update it in the future, because our contracts were not updatable. However now our contracts are updatable and using a separate contract for formulas does not give us any advantages. Moreover, it causes additional Gas wasting.

### Recommendation
Don't use  `AuctionFormula` contract. Keep formulas in contracts that use it.

**Comment by yashnaman** [comment]
>This function uses very often (even several times in one function) and it makes transaction cast very high.
#14 To resolve this in tokens

**Comment by yuriy77k** [comment]
## 4. Function `ensureTransferFrom`

The function [ensureTransferFrom](https://github.com/jointerinc/jointer-token/blob/62da96a472b614d5916c4df2d60cd7c8a3abc492/contracts/Protection/Stacking.sol#L89-L100) is using in many contracts. It checks token balance twice - before and after transaction (it cost about 4000 Gas). But this check is not necessary for most tokens. And definitely not needed for the tokens with which our contract works. If we ever need to work with tokens that do not revert transaction if transfer failed, we can update our contract and add this checking just for such token. But for now no need to waste additional 4000 Gas on every token transfer.
