### ISSUE TITLE
Changing of downside protection ratio can cause issues

### ISSUE THREAD

**Issue by yuriy77k** [jointerinc/jointer-token#2]
The system address has the right to change the downside protection ratio. If downside protection ratio is changed after an investment by a user, the fund diversion to downside protection address at the time of investment v/s the tokens distributed to the user at the end of the auction will result in major issues. This is because the funds shall be transferred as per the old ratio, while tokens shall be distributed as per the new ratio.

In other words, functions [_contributeWithEther](https://github.com/jointerinc/jointer-token/blob/f2a687489748fd7ca7aa1f799b996a8809bc240b/contracts/auctionContracts/Auction.sol#L261) and [_contributeWithToken](https://github.com/jointerinc/jointer-token/blob/f2a687489748fd7ca7aa1f799b996a8809bc240b/contracts/auctionContracts/Auction.sol#L294) use [downSideProtectionRatio](https://github.com/jointerinc/jointer-token/blob/f2a687489748fd7ca7aa1f799b996a8809bc240b/contracts/auctionContracts/Auction.sol#L275) each time when user contributing. 
If after user contributing, owner [change downSideProtectionRatio](https://github.com/jointerinc/jointer-token/blob/f2a687489748fd7ca7aa1f799b996a8809bc240b/contracts/auctionContracts/Auction.sol#L89-L97) then user receive [changed amount of token](https://github.com/jointerinc/jointer-token/blob/f2a687489748fd7ca7aa1f799b996a8809bc240b/contracts/auctionContracts/Auction.sol#L582) at the end of auction day.

When `downSideProtectionRatio` changed, we should not change it immediately, but update only when all tokens will be distributed.

**Comment by mak2296** [comment]
if there 90% downside protection user get only 10% [https://github.com/jointerinc/jointer-token/blob/d8c6efc6ab48c86cbcc57b32e6ee82e52d112408/contracts/auctionContracts/AuctionFormula.sol#L12](url) here you can check

**Comment by yuriy77k** [comment]
You did not fix the issue, more over - create new issues:
1. You restrict the owner to change the ratio when the user invested. In this case, the owner can change the ration only AFTER Auction End and BEFORE new investment come. If will be many investments - this period will be very short.

2. Why you restrict the owner to change [fundWalletRatio](https://github.com/jointerinc/jointer-token/blob/8cadb96b8150387c79b93a0cd497979db5f23d3f/contracts/auctionContracts/Auction.sol#L112-L113)? Changing this ratio does not cause any issue. Remove restriction.

3. As I wrote in description:

> When `downSideProtectionRatio` changed, we should not change it immediately, but update only when all tokens will be distributed.

the issue take place in the token distribution function. This means is you allow change ratio AFTER Auction end, but BEFORE tokens distribution - it does not solve the problem.

**Comment by mak2296** [comment]
Downside ration changed to [DayWiseRatio](https://github.com/jointerinc/jointer-token/blob/be5037a020b29b7e9dea3fc7f990c83071ec81ec/contracts/auctionContracts/Auction.sol#L124) Every Time contribution come we  [check](https://github.com/jointerinc/jointer-token/blob/5d91be6f91d96a623c3794750dab4c4d1e637f59/contracts/auctionContracts/Auction.sol#L276) and when token distributed then also we can  [check](https://github.com/jointerinc/jointer-token/blob/be5037a020b29b7e9dea3fc7f990c83071ec81ec/contracts/auctionContracts/Auction.sol#L561)

**Comment by yuriy77k** [comment]
Good work. Issue fixed.
