### ISSUE TITLE
1:1 tag along process

### ISSUE THREAD

**Issue by yuriy77k** [jointerinc/jointer-token#9]
> The amount that the tag along fund will contribute will be same ratio 1:1 (100%/100%) to the amount that been contribute to **main reserve**. If there is no money on Tag Along, it will not contribute.  
>> For example if today contribution is $100,000 and 90% is locked in downside protection and the other 10% ($10,000) is free, then 90% will go to real estate and the other 10% ($1,000) will go to the liquidity reserve , 90% ($900) will go to Side Reserve and 10% ($100) will go to main reserve, therefore the tag along send $100 to main reserve as well.

There are following issues:

1. The function [contributeTowardAuction]() receives and returns amount in ETH. But you assign [ethAmount](https://github.com/jointerinc/jointer-token/blob/5d91be6f91d96a623c3794750dab4c4d1e637f59/contracts/auctionContracts/AuctionTagAlong.sol#L106) to (ETH value / ETH parice). It's wrong.
This error appeared due to insufficient commenting. The correct code should have a comment before each function with a description of the function, its parameters and return values. For example, like in [Token contract](https://github.com/jointerinc/jointer-token/blob/5d91be6f91d96a623c3794750dab4c4d1e637f59/contracts/Tokens/StandardToken.sol#L161-L166)

2. The [_amount](https://github.com/jointerinc/jointer-token/blob/5d91be6f91d96a623c3794750dab4c4d1e637f59/contracts/auctionContracts/AuctionLiquadity.sol#L444) is a Liquidity amount which include Side + Main reserves.  You send this value, instead of Main reserve value, into [contributeTowardLiquadity](https://github.com/jointerinc/jointer-token/blob/5d91be6f91d96a623c3794750dab4c4d1e637f59/contracts/auctionContracts/AuctionLiquadity.sol#L446-L447).

3. We have to calculate the Main reserve amount (including a reduction)  then request the same value from Tag Along.

**Comment by mak2296** [comment]
1. what is issue here is commenting 
2.we need 1:1 as liquidity as per td you said we only need main reserve only 
3. This is new feature

**Comment by yuriy77k** [comment]
> 1. what is issue here is commenting

Issue is in wrong returns value. You assign to ethAmount the USD value (ETH value / ETH parice), but it should be ETH amount.

> 2. we need 1:1 as liquidity as per td you said we only need main reserve only.

Please, read the latest TD version 6.7. Section: `STEP 5: Tag Along Process`.

![2020-05-11_141042](https://user-images.githubusercontent.com/39490997/81555659-a0784900-9391-11ea-80d6-46768e044377.jpg)

> 3. This is new feature

It's a steps, how you should implement it.

**Comment by mak2296** [comment]
1. Check it changed to new contract
2. It is changed 
3. Calculation changed into Formula Contract
